### ISSUE TITLE
composer require 报错？

### ISSUE THREAD

**Issue by gyp719** [red-jasmine/region#1]
<img width="1167" alt="image" src="https://github.com/red-jasmine/region/assets/30563368/42decff4-c3f6-4fc6-b8fb-ce5f22dc9cd9">

**Comment by liushoukun** [comment]
直接下载数用吧，我后面修改下

**Comment by gyp719** [comment]
只能使用 上传的数据库文件吗？ php artisan regions:crawl-data  提示  Class "PHPHtmlParser\Dom" not found

<img width="954" alt="image" src="https://github.com/red-jasmine/region/assets/30563368/b3eb9227-dc9c-440a-80f3-f398338d8ab1">

**Comment by gyp719** [comment]
composer require paquettg/php-html-parser 这个包 解决

同时 缺少 overtrue/laravel-pinyin
